SET FOREIGN_KEY_CHECKS=0;
UPDATE versao SET versao_codigo='8.3.0'; 
UPDATE versao SET ultima_atualizacao_bd='2013-01-27'; 
UPDATE versao SET ultima_atualizacao_codigo='2013-01-27'; 
UPDATE versao SET versao_bd=146;


ALTER TABLE artefatos_tipo MODIFY artefato_tipo_arquivo VARCHAR(100) DEFAULT NULL;


DROP TABLE IF EXISTS artefato_campo;

CREATE TABLE artefato_campo (
  artefato_campo_id INTEGER(100) UNSIGNED NOT NULL AUTO_INCREMENT,
  artefato_campo_arquivo VARCHAR(255) DEFAULT NULL,
  artefato_campo_campo VARCHAR(255) DEFAULT NULL,
  artefato_campo_descricao VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (artefato_campo_id)
)ENGINE=InnoDB;

DELETE FROM artefato_campo;

INSERT INTO artefato_campo (artefato_campo_arquivo, artefato_campo_campo, artefato_campo_descricao) VALUES 
	('status_pro.html','projeto_cia','organização do projeto'),
	('status_pro.html','projeto_nome','nome do projeto'),
	('status_pro.html','projeto_codigo','código do projeto'),
	('status_pro.html','lista_status','lista de status'),
	('tarefas_atraso_pro.html','projeto_cia','organização do projeto'),
	('tarefas_atraso_pro.html','projeto_nome','nome do projeto'),
	('tarefas_atraso_pro.html','projeto_codigo','código do projeto'),
	('tarefas_atraso_pro.html','tarefas_atraso','tarefas em atraso'),
	('inconscistencia_status_pro.html','projeto_cia','organização do projeto'),
	('inconscistencia_status_pro.html','projeto_nome','nome do projeto'),
	('inconscistencia_status_pro.html','projeto_codigo','código do projeto'),
	('inconscistencia_status_pro.html','lista_inconsistencias','lista de inconsistências'),
	('matriz_stakeholders_pro.html','projeto_cia','organização do projeto'),
	('matriz_stakeholders_pro.html','projeto_nome','nome do projeto'),
	('matriz_stakeholders_pro.html','projeto_codigo','código do projeto'),
	('matriz_stakeholders_pro.html','matriz_stakeholders','matriz de stakeholders'),
	('geral_tarefas_pro.html','projeto_cia','organização do projeto'),
	('geral_tarefas_pro.html','projeto_nome','nome do projeto'),
	('geral_tarefas_pro.html','projeto_codigo','código do projeto'),
	('geral_tarefas_pro.html','geral_tarefas','lista de atividades'),
	('arvore_problema.html','projeto_cia','organização do projeto'),
	('arvore_problema.html','projeto_nome','nome do projeto'),
	('arvore_problema.html','projeto_codigo','código do projeto'),
	('arvore_problema.html','arvore_problema','árvore de problema'),
	('matriz_indicadores.html','projeto_cia','organização do projeto'),
	('matriz_indicadores.html','projeto_nome','nome do projeto'),
	('matriz_indicadores.html','projeto_codigo','código do projeto'),
	('matriz_indicadores.html','projeto_lista_indicadores','lista de indicadores'),
	('mensuracao_projeto.html','demanda_nome','nome da demanda'),
	('mensuracao_projeto.html','demanda_usuario','requisitante da demanda'),
	('mensuracao_projeto.html','demanda_mensurador','mensurador do projeto'),
	('mensuracao_projeto.html','demanda_complexidade','complexidade'),
	('mensuracao_projeto.html','demanda_custo','custo'),
	('mensuracao_projeto.html','demanda_tempo','tempo'),
	('mensuracao_projeto.html','demanda_servidores','servidores'),
	('mensuracao_projeto.html','demanda_recurso_externo','recursos externos'),
	('mensuracao_projeto.html','demanda_interligacao','interligação'),
	('mensuracao_projeto.html','demanda_tamanho','tamanho'),
	('mensuracao_projeto.html','demanda_cia','organização da demanda'),
	('mensuracao_projeto.html','demanda_mensuracao_data','data da mensuração'),
	('ata_reuniao.html','projeto_cia','organização do projeto'),
	('ata_reuniao.html','projeto_nome','nome do projeto'),
	('ata_reuniao.html','projeto_codigo','código do projeto'),
	('ata_reuniao.html','ata_numero','número da ata'),
	('ata_reuniao.html','ata_data_inicio','data de inicio'),
	('ata_reuniao.html','ata_data_fim','data de término'),
	('ata_reuniao.html','ata_local','local da reunião'),
	('ata_reuniao.html','ata_relato','relato'),
	('ata_reuniao.html','ata_proxima_data_inicio','data de inicio da próxima'),
	('ata_reuniao.html','ata_proxima_data_fim','data de término da próxima'),
	('ata_reuniao.html','ata_proxima_local','local da próxima reunião'),
	('ata_reuniao.html','ata_participantes','lista de participantes da ata'),
	('ata_reuniao.html','ata_pauta','pauta da ata'),
	('ata_reuniao.html','ata_acoes','lista de ações'),
	('ata_reuniao.html','ata_pauta_proxima','pauta da próxima reunião'),
	('ata_reuniao.html','ata_assinaturas','lista de assinaturas na pauta'),
	('solicitacao_mudanca.html','projeto_cia','organização do projeto'),
	('solicitacao_mudanca.html','projeto_nome','nome do projeto'),
	('solicitacao_mudanca.html','projeto_codigo','código do projeto'),
	('solicitacao_mudanca.html','projeto_mudanca_numero','número da solicitação'),
	('solicitacao_mudanca.html','projeto_mudanca_cliente','demandante'),
	('solicitacao_mudanca.html','projeto_mudanca_responsavel','responsável pela solicitação'),
	('solicitacao_mudanca.html','projeto_mudanca_autoridade','autoridade que aprova a solicitação'),
	('solicitacao_mudanca.html','projeto_mudanca_justificativa','justificativa'),
	('solicitacao_mudanca.html','projeto_mudanca_parecer_tecnico','parecer técnico'),
	('solicitacao_mudanca.html','projeto_mudanca_solucoes','soluções possíveis'),
	('solicitacao_mudanca.html','projeto_mudanca_impacto_cronograma','impacto no cronograma'),
	('solicitacao_mudanca.html','projeto_mudanca_impacto_custo','impacto no custo'),
	('solicitacao_mudanca.html','projeto_mudanca_novo_risco','novo risco'),
	('solicitacao_mudanca.html','projeto_mudanca_outros_impactos','outros impactos'),
	('solicitacao_mudanca.html','projeto_mudanca_solucao','solução pela equipe'),
	('solicitacao_mudanca.html','projeto_mudanca_parecer','parecer'),
	('solicitacao_mudanca.html','projeto_mudanca_requisitante_aprovada','aprovada pelo requisitante'),
	('solicitacao_mudanca.html','projeto_mudanca_requisitante_reprovada','reprovada pelo requisitante'),
	('solicitacao_mudanca.html','projeto_mudanca_administracao_aprovada','aprovada pela administração'),
	('solicitacao_mudanca.html','projeto_mudanca_administracao_reprovada','reprovada pela administração'),
	('solicitacao_mudanca.html','projeto_mudanca_data','data da solicitação'),
	('solicitacao_mudanca.html','projeto_mudanca_data_aprovacao','data da aprovação'),
	('termo_recebimento.html','projeto_cia','organização do projeto'),
	('termo_recebimento.html','projeto_nome','nome do projeto'),
	('termo_recebimento.html','projeto_codigo','código do projeto'),
	('termo_recebimento.html','projeto_recebimento_numero','número do recebimento'),
	('termo_recebimento.html','projeto_recebimento_cliente','responsável pelo recebimento'),
	('termo_recebimento.html','recebimento_dados_cliente','dados do responsável pelo recebimento'),
	('termo_recebimento.html','projeto_recebimento_responsavel','responsável pela entrega'),
	('termo_recebimento.html','recebimento_dados_responsavel','dados do responsável pela entrega'),
	('termo_recebimento.html','projeto_recebimento_tipo','tipo de recebimento'),
	('termo_recebimento.html','projeto_recebimento_lista','lista de produtos/serviços'),
	('termo_recebimento.html','projeto_recebimento_observacao','observação quanto ao recebimento'),
	('termo_recebimento.html','projeto_recebimento_data_entrega','data do recebimento'),
	('termo_encerramento.html','projeto_cia','organização do projeto'),
	('termo_encerramento.html','projeto_nome','nome do projeto'),
	('termo_encerramento.html','projeto_codigo','código do projeto'),
	('termo_encerramento.html','projeto_encerramento_responsavel','responsável pelo encerramento'),
	('termo_encerramento.html','encerramento_dados_responsavel','dados do responsável pelo encerramento'),
	('termo_encerramento.html','projeto_encerramento_decisao','decisão quanto ao encerramento'),
	('termo_encerramento.html','projeto_encerramento_justificativa','justificativa'),
	('termo_encerramento.html','projeto_encerramento_data','data do encerramento'),
	('licoes_aprendidas.html','projeto_cia','organização do projeto'),
	('licoes_aprendidas.html','projeto_nome','nome do projeto'),
	('licoes_aprendidas.html','projeto_codigo','código do projeto'),
	('licoes_aprendidas.html','licao','lista de lições aprendidas'),
	('gerenciamento_risco.html','projeto_cia','organização do projeto'),
	('gerenciamento_risco.html','projeto_nome','nome do projeto'),
	('gerenciamento_risco.html','projeto_codigo','código do projeto'),
	('gerenciamento_risco.html','projeto_risco_usuario','id do responsável pelo gerenciamento de risco'),
	('gerenciamento_risco.html','projeto_risco_descricao','descrição do gerenciamento de risco'),
	('gerenciamento_risco.html','projeto_risco_data','data de alteração do gerenciamento de risco'),
	('gerenciamento_risco.html','projeto_risco_tipo','lista de riscos'),
	('plano_gerenciamento.html','projeto_cia','organização do projeto'),
	('plano_gerenciamento.html','projeto_nome','nome do projeto'),
	('plano_gerenciamento.html','projeto_codigo','código do projeto'),
	('plano_gerenciamento.html','projeto_embasamento_responsavel','id do responsável pelo plano de comunicação'),
	('plano_gerenciamento.html','projeto_embasamento_justificativa','data de alteração'),
	('plano_gerenciamento.html','projeto_embasamento_objetivo','data de alteração'),
	('plano_gerenciamento.html','projeto_embasamento_escopo','data de alteração'),
	('plano_gerenciamento.html','estrutura_analitica','estrutura analítica de projetos'),
	('plano_gerenciamento.html','dicionario_eap','dicionário da eap'),
	('plano_gerenciamento.html','projeto_embasamento_nao_escopo','não escopo'),
	('plano_gerenciamento.html','projeto_embasamento_premissas','data de alteração'),
	('plano_gerenciamento.html','projeto_embasamento_restricoes','data de alteração'),
	('plano_gerenciamento.html','cronograma_marco','cronograma de marcos'),
	('plano_gerenciamento.html','orcamento','orçamento e fonte de recurso'),
	('plano_gerenciamento.html','projeto_qualidade_descricao','descrição do plano de qualidade'),
	('plano_gerenciamento.html','projeto_qualidade_entrega','entregas do plano de qualidade'),
	('plano_gerenciamento.html','organograma_projeto','organograma do projeto'),
	('plano_gerenciamento.html','equipe_projeto','equipe do projeto'),
	('plano_gerenciamento.html','responsabilidades','responsabilidades da equipe do projeto'),
	('plano_gerenciamento.html','projeto_comunicacao_descricao','descrição do processo de comunicação'),
	('plano_gerenciamento.html','projeto_comunicacao_evento','lista de eventos de comunicação'),
	('plano_gerenciamento.html','projeto_risco_descricao','descrição do processo de gerenciamento de riscos'),
	('plano_gerenciamento.html','projeto_risco_tipo','lista de riscos'),
	('plano_gerenciamento.html','aquisicoes_projeto','plano de aquisições e contratações'),
	('plano_gerenciamento.html','projeto_embasamento_data','data de alteração'),
	('plano_comunicacoes.html','projeto_cia','organização do projeto'),
	('plano_comunicacoes.html','projeto_nome','nome do projeto'),
	('plano_comunicacoes.html','projeto_codigo','código do projeto'),
	('plano_comunicacoes.html','projeto_comunicacao_usuario','id do responsável pelo plano de comunicação'),
	('plano_comunicacoes.html','projeto_comunicacao_descricao','descrição do processo de comunicação'),
	('plano_comunicacoes.html','projeto_comunicacao_data','data de alteração'),
	('plano_comunicacoes.html','projeto_comunicacao_evento','lista de eventos de comunicação'),
	('plano_qualidade.html','projeto_cia','organização do projeto'),
	('plano_qualidade.html','projeto_nome','nome do projeto'),
	('plano_qualidade.html','projeto_codigo','código do projeto'),
	('plano_qualidade.html','projeto_qualidade_usuario','id do responsável pelo plano de qualidade'),
	('plano_qualidade.html','projeto_qualidade_descricao','descrição do plano de qualidade'),
	('plano_qualidade.html','projeto_qualidade_data','data de alteração'),
	('plano_qualidade.html','projeto_qualidade_entrega','lista de entregas'),
	('embasamento_projeto.html','projeto_cia','organização do projeto'),
	('embasamento_projeto.html','projeto_nome','nome do projeto'),
	('embasamento_projeto.html','projeto_codigo','código do projeto'),
	('embasamento_projeto.html','projeto_embasamento_responsavel','id do responsável pelos dados'),
	('embasamento_projeto.html','projeto_embasamento_justificativa','justificativa'),
	('embasamento_projeto.html','projeto_embasamento_objetivo','objetivo'),
	('embasamento_projeto.html','projeto_embasamento_escopo','escopo'),
	('embasamento_projeto.html','projeto_embasamento_nao_escopo','não escopo'),
	('embasamento_projeto.html','projeto_embasamento_premissas','premissas'),
	('embasamento_projeto.html','projeto_embasamento_restricoes','restrições'),
	('embasamento_projeto.html','projeto_embasamento_orcamento','orçamento e recursos'),
	('embasamento_projeto.html','projeto_embasamento_data','data de alteração'), 
	('termo_abertura.html','projeto_abertura_cia','organização do termo de abertura'),
	('termo_abertura.html','projeto_abertura_nome','nome do projeto'),
	('termo_abertura.html','projeto_abertura_codigo','código do termo de abertura'),
	('termo_abertura.html','projeto_abertura_responsavel','responsável pelo termo de abertura'),
	('termo_abertura.html','projeto_abertura_autoridade','responsável pela aprovação do termo de abertura'),
	('termo_abertura.html','projeto_abertura_justificativa','justificativa'),
	('termo_abertura.html','projeto_abertura_objetivo','objetivo'),
	('termo_abertura.html','projeto_abertura_escopo','escopo'),
	('termo_abertura.html','projeto_abertura_nao_escopo','não escopo'),
	('termo_abertura.html','projeto_abertura_tempo','tempo'),
	('termo_abertura.html','projeto_abertura_custo','custo'),
	('termo_abertura.html','projeto_abertura_premissas','premissas'),
	('termo_abertura.html','projeto_abertura_restricoes','restrições'),
	('termo_abertura.html','projeto_abertura_riscos','riscos'),
	('termo_abertura.html','projeto_abertura_patrocinadores','patrocinadores'),
	('termo_abertura.html','projeto_abertura_gerente_projeto','gerente do projeto'),
	('termo_abertura.html','projeto_abertura_usuarios','equipe do projeto'),
	('termo_abertura.html','projeto_abertura_interessados','partes interessadas'),
	('termo_abertura.html','projeto_abertura_infraestrutura','infraestrutura'),
	('termo_abertura.html','projeto_abertura_data','data'),
	('termo_abertura.html','projeto_abertura_observacao','observações'),
	('estudo_viabilidade.html','projeto_viabilidade_cia','organização do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_nome','nome do projeto'),
	('estudo_viabilidade.html','projeto_viabilidade_codigo','código do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_necessidade','necessidade do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_alinhamento','alinhamento estratégico do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_requisitos','requisitos do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_solucoes','soluções do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_viabilidade_tecnica','viabilidade técnica do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_financeira','viabilidade financeira do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_institucional','viabilidade institucional do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_solucao','soluções do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_continuidade','continuidade do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_responsavel','responsável pelo estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_data','data do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_interessados','lista de partes interessadas'),
	('estudo_viabilidade.html','projeto_viabilidade_patrocinadores','lista de patrocinadores'),
	('estudo_viabilidade.html','projeto_viabilidade_usuarios','lista de equipe do estudo'),
	('estudo_viabilidade.html','projeto_viabilidade_tempo','tempo do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_custo','custo do estudo de viabilidade'),
	('estudo_viabilidade.html','projeto_viabilidade_observacao','observações do estudo de viabilidade'),
	('demanda.html','demanda_nome','nome da demanda'),
	('demanda.html','demanda_usuario','requisitante da demanda'),
	('demanda.html','demanda_identificacao','identificação da demanda'),
	('demanda.html','demanda_justificativa','justificativa da demanda'),
	('demanda.html','demanda_resultados','resultados esperados da demanda'),
	('demanda.html','demanda_alinhamento','alinhamento da demanda'),
	('demanda.html','demanda_fonte_recurso','fonte de recurso para a demanda'),
	('demanda.html','demanda_cia','organização da demanda'),
	('demanda.html','demanda_data','data da solicitação da demanda'),
	('demanda.html','demanda_prazo','prazo da demanda'),
	('demanda.html','demanda_custos','custos da demanda'),
	('demanda.html','demanda_observacao','observações da demanda');




INSERT INTO campo_formulario (campo_formulario_tipo, campo_formulario_campo, campo_formulario_descricao, campo_formulario_ativo) VALUES 
	('perspectiva','pg_perspectiva_descricao','Descrição',1),
	('perspectiva','pg_perspectiva_oque','O que',1),
	('perspectiva','pg_perspectiva_onde','Onde',1),
	('perspectiva','pg_perspectiva_quando','Quando',1),
	('perspectiva','pg_perspectiva_como','Como',1),
	('perspectiva','pg_perspectiva_porque','Porque',1),
	('perspectiva','pg_perspectiva_quanto','Quanto',1),
	('perspectiva','pg_perspectiva_quem','Quem',1),
	('perspectiva','pg_perspectiva_controle','Controle',1),
	('perspectiva','pg_perspectiva_melhorias','Melhorias',1),
	('perspectiva','pg_perspectiva_metodo_aprendizado','Metodo de aprendizado',1),
	('perspectiva','pg_perspectiva_desde_quando','Desde quando',1),
	('perspectiva','pg_perspectiva_superior','Perspectiva superior',1),
	('tema','tema_descricao','Descrição',1),
	('tema','tema_oque','O que',1),
	('tema','tema_onde','Onde',1),
	('tema','tema_quando','Quando',1),
	('tema','tema_como','Como',1),
	('tema','tema_porque','Porque',1),
	('tema','tema_quanto','Quanto',1),
	('tema','tema_quem','Quem',1),
	('tema','tema_controle','Controle',1),
	('tema','tema_melhorias','Melhorias',1),
	('tema','tema_metodo_aprendizado','Metodo de aprendizado',1),
	('tema','tema_desde_quando','Desde quando',1),
	('tema','tema_superior','Tema superior',1),
	('objetivo','pg_objetivo_estrategico_descricao','Descrição',1),
	('objetivo','pg_objetivo_estrategico_oque','O que',1),
	('objetivo','pg_objetivo_estrategico_onde','Onde',1),
	('objetivo','pg_objetivo_estrategico_quando','Quando',1),
	('objetivo','pg_objetivo_estrategico_como','Como',1),
	('objetivo','pg_objetivo_estrategico_porque','Porque',1),
	('objetivo','pg_objetivo_estrategico_quanto','Quanto',1),
	('objetivo','pg_objetivo_estrategico_quem','Quem',1),
	('objetivo','pg_objetivo_estrategico_controle','Controle',1),
	('objetivo','pg_objetivo_estrategico_melhorias','Melhorias',1),
	('objetivo','pg_objetivo_estrategico_metodo_aprendizado','Metodo de aprendizado',1),
	('objetivo','pg_objetivo_estrategico_desde_quando','Desde quando',1),
	('objetivo','pg_objetivo_estrategico_composicao','Composição',1),	
	('objetivo','pg_objetivo_estrategico_superior','Objetivo estratégico superior',1),
	('objetivo','pg_objetivo_estrategico_composicao','Composição de objetivos estratégicos',1),
	('fator','pg_fator_critico_descricao','Descrição',1),
	('fator','pg_fator_critico_oque','O que',1),
	('fator','pg_fator_critico_onde','Onde',1),
	('fator','pg_fator_critico_quando','Quando',1),
	('fator','pg_fator_critico_como','Como',1),
	('fator','pg_fator_critico_porque','Porque',1),
	('fator','pg_fator_critico_quanto','Quanto',1),
	('fator','pg_fator_critico_quem','Quem',1),
	('fator','pg_fator_critico_controle','Controle',1),
	('fator','pg_fator_critico_melhorias','Melhorias',1),
	('fator','pg_fator_critico_metodo_aprendizado','Metodo de aprendizado',1),
	('fator','pg_fator_critico_desde_quando','Desde quando',1),
	('fator','pg_fator_critico_tipo','Tipo',1),
	('estrategia','pg_estrategia_descricao','Descrição',1),
	('estrategia','pg_estrategia_oque','O que',1),
	('estrategia','pg_estrategia_onde','Onde',1),
	('estrategia','pg_estrategia_quando','Quando',1),
	('estrategia','pg_estrategia_como','Como',1),
	('estrategia','pg_estrategia_porque','Porque',1),
	('estrategia','pg_estrategia_quanto','Quanto',1),
	('estrategia','pg_estrategia_quem','Quem',1),
	('estrategia','pg_estrategia_controle','Controle',1),
	('estrategia','pg_estrategia_melhorias','Melhorias',1),
	('estrategia','pg_estrategia_metodo_aprendizado','Metodo de aprendizado',1),
	('estrategia','pg_estrategia_desde_quando','Desde quando',1),
	('estrategia','pg_estrategia_tipo','Tipo',1),	
	('estrategia','pg_estrategia_codigo','Código',1),	
	('estrategia','pg_estrategia_composicao','Composição de iniciativas estratégicas',1),
	('meta','pg_meta_descricao','Descrição',1),
	('meta','pg_meta_oque','O que',1),
	('meta','pg_meta_onde','Onde',1),
	('meta','pg_meta_quando','Quando',1),
	('meta','pg_meta_como','Como',1),
	('meta','pg_meta_porque','Porque',1),
	('meta','pg_meta_quanto','Quanto',1),
	('meta','pg_meta_quem','Quem',1),
	('meta','pg_meta_controle','Controle',1),
	('meta','pg_meta_melhorias','Melhorias',1),
	('meta','pg_meta_metodo_aprendizado','Metodo de aprendizado',1),
	('meta','pg_meta_desde_quando','Desde quando',1),
	('meta','pg_meta_tipo','Tipo',1),	
	('pratica','pratica_descricao','Descrição',1),
	('pratica','pratica_oque','O que',1),
	('pratica','pratica_onde','Onde',1),
	('pratica','pratica_quando','Quando',1),
	('pratica','pratica_como','Como',1),
	('pratica','pratica_porque','Porque',1),
	('pratica','pratica_quanto','Quanto',1),
	('pratica','pratica_quem','Quem',1),
	('pratica','pratica_controle','Controle',1),
	('pratica','pratica_melhorias','Melhorias',1),
	('pratica','pratica_metodo_aprendizado','Metodo de aprendizado',1),
	('pratica','pratica_desde_quando','Desde quando',1),
	('pratica','pratica_composicao','Composição de práticas de gestão',1),
	('indicador','pratica_indicador_descricao','Descrição',1),
	('indicador','pratica_indicador_oque','O que',1),
	('indicador','pratica_indicador_onde','Onde',1),
	('indicador','pratica_indicador_quando','Quando',1),
	('indicador','pratica_indicador_como','Como',1),
	('indicador','pratica_indicador_porque','Porque',1),
	('indicador','pratica_indicador_quanto','Quanto',1),
	('indicador','pratica_indicador_quem','Quem',1),
	('indicador','pratica_indicador_controle','Controle',1),
	('indicador','pratica_indicador_melhorias','Melhorias',1),
	('indicador','pratica_indicador_metodo_aprendizado','Metodo de aprendizado',1),
	('indicador','pratica_indicador_desde_quando','Desde quando',1),
	('acao','plano_acao_descricao','Descrição',1),
	('acao','plano_acao_codigo','Código',1),
	('planejamento ','perfil','Menu de perfil da organização',1),
	('planejamento ','estrutura','Estrutura Organizacional',1),
	('planejamento ','fornecedores','Fornecedores e Insumos',1),
	('planejamento ','processos','Processos e Produtos',1),
	('planejamento ','clientes','Clientes/Usuários',1),
	('planejamento ','pessoal','Quadro de Pessoal',1),
	('planejamento ','programa','Programas e Ações',1),
	('planejamento ','premiacao','Premiação em Gestão',1);
