SET FOREIGN_KEY_CHECKS=0;
UPDATE versao SET versao_codigo='8.0.38'; 
UPDATE versao SET ultima_atualizacao_bd='2012-10-14'; 
UPDATE versao SET ultima_atualizacao_codigo='2012-10-14'; 
UPDATE versao SET versao_bd=124; 

INSERT INTO config (config_nome, config_valor, config_grupo, config_tipo) VALUES 
	('login','login','legenda','text');

ALTER TABLE contatos CHANGE contato_nomeguerra contato_nomeguerra VARCHAR(100) DEFAULT NULL;

ALTER TABLE cias ADD COLUMN cia_cnpj VARCHAR(18) DEFAULT NULL;
ALTER TABLE cias ADD COLUMN cia_inscricao_estadual VARCHAR(25) DEFAULT NULL;

CREATE TABLE categoria (
  categoria_id INTEGER(100) UNSIGNED NOT NULL AUTO_INCREMENT,
  categoria_nome VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (categoria_id)
)ENGINE=InnoDB;

INSERT INTO categoria (categoria_id, categoria_nome) VALUES
	(1,'Comércio'),
	(2,'Organizações Industriais'),
	(3,'Organizações prestadoras de serviço'),
	(4,'Organizações sociais sem fins lucrativos'),
	(5,'Órgãos da administração pública Estadual'),
	(6,'Órgão da administração pública Federal'),
	(7,'Órgãos da administração pública Municipal');

CREATE TABLE segmento (
  segmento_id INTEGER(100) UNSIGNED NOT NULL AUTO_INCREMENT,
  segmento_categoria INTEGER(100) UNSIGNED DEFAULT NULL,
  segmento_nome VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (segmento_id),
  KEY segmento_categoria (segmento_categoria),
  CONSTRAINT segmento_fk FOREIGN KEY (segmento_categoria) REFERENCES categoria (categoria_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

INSERT INTO segmento (segmento_categoria, segmento_nome) VALUES
	(1,'Comércio Varejista de gêneros alimentícios'),
	(1,'Comércio Varejista'),
	(1,'Distribuidores, Revendedores, Comércio Atacadista'),
	(2,'Aeronáutica/Aeroespacial'),
	(2,'Alimentos e Bebidas'),
	(2,'Bélica'),
	(2,'Construção Civil'),
	(2,'Construção Naval'),
	(2,'Elétrica'),
	(2,'Eletrônica'),
	(2,'Gráfica'),
	(2,'Informática'),
	(2,'Máquinas e Equipamentos'),
	(2,'Material de Construção'),
	(2,'Material de Embalagem'),
	(2,'Medicamentos, Higiene, Prod. Médicos e Odontológicos'),
	(2,'Metalúrgica'),
	(2,'Mineração'),
	(2,'Mobiliário e Decoração'),
	(2,'Nuclear'),
	(2,'Outras indústrias, ou combinações acima'),
	(2,'Papel e Celulose'),
	(2,'Produtos Ótico, Instrumentos'),
	(2,'Produtos e Artefatos de Madeira e Couro'),
	(2,'Produtos e Equipamentos de Cultura, Esporte e Lazer'),
	(2,'Química, Petroquímica, Alcoolquímica, Borracha e Plástico'),
	(2,'Têxtil'),
	(2,'Têxtil'),
	(2,'Veículos, Equipamentos de Transporte e Manuseio'),
	(3,'Administradoras'),
	(3,'Agropecuários'),
	(3,'Alimentos e Bebidas'),
	(3,'Arquitetura'),
	(3,'Assessoramento'),
	(3,'Bancos e Instituições Financeiras'),
	(3,'Comércio Exterior'),
	(3,'Comunicações (Rádio, Jornal, TV, Telecomunicações)'),
	(3,'Conservação e Limpeza'),
	(3,'Construção e Montagens'),
	(3,'Consultoria e Engenharia'),
	(3,'Consultoria em Administração'),
	(3,'Contabilidade'),
	(3,'Cultura, Esporte e Lazer'),
	(3,'Dentista'),
	(3,'Educação'),
	(3,'Eventos'),
	(3,'Farmácia'),
	(3,'Fundações, Associações, Federações, Sindicatos, etc'),
	(3,'Gráficas'),
	(3,'Hospitais'),
	(3,'Hotéis e Restaurantes'),
	(3,'Imobiliárias'),
	(3,'Informática'),
	(3,'Jurídico'),
	(3,'Laboratórios'),
	(3,'Manutenção'),
	(3,'Outros ou combinação dos acima'),
	(3,'Públicos (gás, luz, telefone, água e esgoto etc.)'),
	(3,'Profissionais'),
	(3,'Publicidade'),
	(3,'Qualidade (Consultoria, Inspeção, etc.)'),
	(3,'Saúde'),
	(3,'Segurança'),
	(3,'Seguros'),
	(3,'Serviço Social'),
	(3,'Telefonia'),
	(3,'Transporte, Armazenagem'),
	(3,'Turismo'),
	(3,'Veículos'),
	(4,'Assistência Social'),
	(4,'Educação'),
	(4,'Meio Ambiente'),
	(4,'Outros'),
	(4,'Saúde'),
	(5,'Abastecimento'),
	(5,'Administração'),
	(5,'Agropecuária e Pesca'),
	(5,'Auditoria'),
	(5,'Comércio Exterior'),
	(5,'Comunicações'),
	(5,'Cultura'),
	(5,'Defesa Nacional'),
	(5,'Direito Público'),
	(5,'Esporte e Lazer'),
	(5,'Finanças'),
	(5,'Indústria e Comércio'),
	(5,'Meio-ambiente'),
	(5,'Minas e Energia'),
	(5,'Ocupação Territorial e Reforma Agrária'),
	(5,'Pesquisa Científica e Tecnológica'),
	(5,'Planejamento e Orçamento'),
	(5,'Previdência e Assistência Social'),
	(5,'Relações Exteriores'),
	(5,'Saúde'),
	(5,'Segurança'),
	(5,'Serviços Tecnológicos'),
	(5,'Trabalho'),
	(5,'Transporte'),
	(5,'Turismo'),
	(6,'Abastecimento'),
	(6,'Administração'),
	(6,'Agropecuária e Pesca'),
	(6,'Auditoria'),
	(6,'Comércio Exterior'),
	(6,'Comunicações'),
	(6,'Cultura'),
	(6,'Defesa Nacional'),
	(6,'Direito Público'),
	(6,'Esporte e Lazer'),
	(6,'Finanças'),
	(6,'Indústria e Comércio'),
	(6,'Meio-ambiente'),
	(6,'Minas e Energia'),
	(6,'Ocupação Territorial e Reforma Agrária'),
	(6,'Outros, ou combinação dos acima'),
	(6,'Pesquisa Cientifica e Tecnológica'),
	(6,'Planejamento e Orçamento'),
	(6,'Previdência e Assistência Social'),
	(6,'Relações Exteriores'),
	(6,'Saúde'),
	(6,'Segurança'),
	(6,'Serviços Tecnológicos'),
	(6,'Trabalho'),
	(6,'Transporte'),
	(6,'Turismo'),
	(7,'Abastecimento'),
	(7,'Administração'),
	(7,'Agropecuária e Pesca'),
	(7,'Auditoria'),
	(7,'Comércio Exterior'),
	(7,'Comunicações'),
	(7,'Cultura'),
	(7,'Defesa Nacional '),
	(7,'Direito Público'),
	(7,'Escola'),
	(7,'Esporte e Lazer'),
	(7,'Finanças'),
	(7,'Indústria e Comércio'),
	(7,'Meio-ambiente'),
	(7,'Minas e Energia'),
	(7,'Ocupação Territorial e Reforma Agrária'),
	(7,'Outros, ou combinação dos acima'),
	(7,'Pesquisa Cientifica e Tecnológica'),
	(7,'Planejamento e Orçamento'),
	(7,'Prefeitura'),
	(7,'Previdência e Assistência Social'),
	(7,'Relações Exteriores'),
	(7,'Saúde'),
	(7,'Segurança'),
	(7,'Serviços Tecnológicos'),
	(7,'Trabalho'),
	(7,'Transporte'),
	(7,'Turismo');



CREATE TABLE cia_segmento (
  cia_segmento_cia INTEGER(100) UNSIGNED DEFAULT NULL,
  cia_segmento_segmento INTEGER(100) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (cia_segmento_cia, cia_segmento_segmento),
  KEY cia_segmento_cia (cia_segmento_cia),
  KEY cia_segmento_segmento (cia_segmento_segmento),
  CONSTRAINT cia_segmentos_fk FOREIGN KEY (cia_segmento_cia) REFERENCES cias (cia_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cia_segmentos_fk1 FOREIGN KEY (cia_segmento_segmento) REFERENCES segmento (segmento_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;


