UPDATE versao SET versao_bd=20; 

ALTER TABLE recursos ADD COLUMN recurso_ev VARCHAR(20) DEFAULT NULL;
ALTER TABLE recursos ADD COLUMN recurso_esf VARCHAR(20) DEFAULT NULL;
ALTER TABLE recursos ADD COLUMN recurso_ptres VARCHAR(20) DEFAULT NULL;
ALTER TABLE recursos ADD COLUMN recurso_fonte VARCHAR(20) DEFAULT NULL;
ALTER TABLE recursos ADD COLUMN recurso_sb VARCHAR(20) DEFAULT NULL;
ALTER TABLE recursos ADD COLUMN recurso_ugr VARCHAR(20) DEFAULT NULL;
ALTER TABLE recursos ADD COLUMN recurso_pi VARCHAR(20) DEFAULT NULL;

ALTER TABLE tarefa_log MODIFY tarefa_log_nd VARCHAR(15); 