SET FOREIGN_KEY_CHECKS=0;
UPDATE versao SET versao_codigo='8.0.16'; 
UPDATE versao SET ultima_atualizacao_bd='2012-04-01'; 
UPDATE versao SET ultima_atualizacao_codigo='2012-04-01'; 
UPDATE versao SET versao_bd=99;
ALTER TABLE tarefa_gastos CHANGE tarefa_custos_data_recebido tarefa_gastos_data_recebido DATE DEFAULT NULL;
ALTER TABLE tema_log ADD COLUMN tema_log_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE tema_log ADD COLUMN tema_log_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE estrategias_log ADD COLUMN pg_estrategia_log_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE estrategias_log ADD COLUMN pg_estrategia_log_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE fatores_criticos_log ADD COLUMN pg_fator_criticos_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE fatores_criticos_log ADD COLUMN pg_fator_criticos_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE metas_log ADD COLUMN pg_meta_log_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE metas_log ADD COLUMN pg_meta_log_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE objetivos_estrategicos_log ADD COLUMN pg_objetivo_estrategico_log_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE objetivos_estrategicos_log ADD COLUMN pg_objetivo_estrategico_log_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_custos ADD COLUMN plano_acao_item_custos_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_custos ADD COLUMN plano_acao_item_custos_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_gastos ADD COLUMN plano_acao_item_gastos_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_gastos ADD COLUMN plano_acao_item_gastos_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_h_custos ADD COLUMN h_custos_metodo1 INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_h_custos ADD COLUMN h_custos_metodo2 INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_h_custos ADD COLUMN h_custos_exercicio1 INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_h_custos ADD COLUMN h_custos_exercicio2 INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_h_gastos ADD COLUMN h_gastos_metodo1 INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_h_gastos ADD COLUMN h_gastos_metodo2 INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_h_gastos ADD COLUMN h_gastos_exercicio1 INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_item_h_gastos ADD COLUMN h_gastos_exercicio2 INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_log ADD COLUMN plano_acao_log_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE plano_acao_log ADD COLUMN plano_acao_log_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE pratica_indicador_log ADD COLUMN pratica_indicador_log_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE pratica_indicador_log ADD COLUMN pratica_indicador_log_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE pratica_log ADD COLUMN pratica_log_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE pratica_log ADD COLUMN pratica_log_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_gastos ADD COLUMN tarefa_gastos_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_log ADD COLUMN tarefa_log_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_log ADD COLUMN tarefa_log_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE baseline_tarefa_custos ADD COLUMN tarefa_custos_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE baseline_tarefa_custos ADD COLUMN tarefa_custos_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE baseline_tarefa_gastos ADD COLUMN tarefa_gastos_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE baseline_tarefa_gastos ADD COLUMN tarefa_gastos_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_custos ADD COLUMN tarefa_custos_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_custos ADD COLUMN tarefa_custos_exercicio INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_gastos ADD COLUMN tarefa_gastos_metodo INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_h_custos ADD COLUMN h_custos_metodo1 INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_h_custos ADD COLUMN h_custos_metodo2 INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_h_custos ADD COLUMN h_custos_exercicio1 INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_h_custos ADD COLUMN h_custos_exercicio2 INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_h_gastos ADD COLUMN h_gastos_metodo1 INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_h_gastos ADD COLUMN h_gastos_metodo2 INTEGER(100) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_h_gastos ADD COLUMN h_gastos_exercicio1 INTEGER(4) UNSIGNED DEFAULT NULL;
ALTER TABLE tarefa_h_gastos ADD COLUMN h_gastos_exercicio2 INTEGER(4) UNSIGNED DEFAULT NULL;